# Ruby Native reads this file on launch to configure the native app.
# https://rubynative.com/docs

app:
  mode: advanced
  entry_path: /

tabs:
  - title: Home
    path: /
    icon: house
  - title: Profile
    path: /profile
    icon: person
